CREATE TABLE USER
 ( 
     ID VARCHAR (36)  NOT NULL , 
     USERNAME VARCHAR (36) NOT NULL, 
     PASSWORD VARCHAR (36) NOT NULL
);

INSERT INTO USER(ID,USERNAME,PASSWORD) VALUES('1','cc','cc');
INSERT INTO USER(ID,USERNAME,PASSWORD) VALUES('2','dd','dd');